spring:
  cloud:
    config:
      server:
        git:
           uri: file://Users/Lendy/Documents/sample-config
           
#          uri: https://github.com/u8921013/sample-config
# While in development mode, you can configure the config server to pick up configuration files from
# the file system
          
#           uri: file://Users/anilallewar/Documents/Anil Allewar/Trainings/Code Samples/Enterprise Java/Micro Services/sample-config

# Defines the port where the config server is running so that rest of the services can pick up 
# their external configurations
server:
  port: 7001        
---

spring:
  profiles: docker
  cloud:
     config:
       server:
        git:
           uri: https://github.com/u8921013/sample-config

server:
  port: 7001 
